### get
get http://localhost:4000/user-api/users

### post
post http://localhost:4000/user-api/user
Content-Type:  application/json

{
    "userId": 512,
    "username": "Nireekshan",
    "age": 23,
    "marks": [
        90,
        92,34,45
    ],
    "address": {
       "city": "Vijayawada"
    }
}

### put
put http://localhost:4000/user-api/user
Content-Type: application/json

{
    "id":201,
    "name":"charan"
}


### delete
delete http://localhost:4000/user-api/user
